"""
generate_phase5_figures.py
Generate Phase 5 publication-quality figures using ONLY the 7 leakage-free signals.

Produces:
  - Figure 8: Feature Importance (7 signals, normalized to sum=1.0)
  - Figure 9: Signal Correlation Matrix (7x7 heatmap)
  - Figure 10: Signal Distributions (2x4 grid for 7 signals + empty)
  - Figure 13: Ablation Delta (performance drop when dropping each signal)

Reads data from leakage_free_report.json (generated by evaluate_leakage_free.py).
"""

import json
import sys
from pathlib import Path

import numpy as np

RESULTS_DIR = Path("/home/prashanna/Documents/Guardrailer/evaluation_results")
FIGURES_DIR = RESULTS_DIR / "figures"
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
REPORT_PATH = RESULTS_DIR / "leakage_free_report.json"

PHASE5_SIGNALS = [
    "centroid",
    "length_norm",
    "token_freq",
    "perplexity",
    "entropy",
    "sparse_idf",
    "ngram",
]

SIGNAL_DISPLAY_NAMES = {
    "centroid": "Centroid Distance",
    "length_norm": "Length Normalization",
    "token_freq": "Token Frequency",
    "perplexity": "Perplexity",
    "entropy": "Entropy Analysis",
    "sparse_idf": "Sparse IDF",
    "ngram": "N-gram Overlap",
}


def generate_figures(report_path: Path = REPORT_PATH) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.colors as mcolors
    except ImportError:
        print("ERROR: matplotlib not installed. Run: pip install matplotlib")
        sys.exit(1)

    with open(report_path) as f:
        report = json.load(f)

    plt.rcParams.update({
        "figure.dpi": 200,
        "savefig.dpi": 200,
        "font.size": 11,
        "axes.titlesize": 13,
        "axes.labelsize": 11,
        "font.family": "sans-serif",
    })

    # -----------------------------------------------------------------------
    # Figure 8: Feature Importance (7 signals only)
    # -----------------------------------------------------------------------
    fi = report.get("feature_importance", {})
    signals_ordered = [s for s in PHASE5_SIGNALS if s in fi]
    importances = [fi[s] for s in signals_ordered]
    total_imp = sum(importances)
    importances_norm = [imp / total_imp for imp in importances] if total_imp > 0 else importances
    display_names = [SIGNAL_DISPLAY_NAMES.get(s, s) for s in signals_ordered]

    fig, ax = plt.subplots(figsize=(10, 5))
    colors_fi = ["#1976D2", "#388E3C", "#F57C00", "#7B1FA2", "#D32F2F", "#00796B", "#455A64"]
    bars = ax.barh(display_names[::-1], importances_norm[::-1],
                   color=colors_fi[:len(signals_ordered)][::-1], height=0.55, edgecolor="white", linewidth=0.5)
    ax.set_xlim(0, max(importances_norm) * 1.15)
    ax.set_xlabel("Feature Importance (normalized)")
    ax.set_title("Phase 5: Random Forest Feature Importance (7 Leakage-Free Signals)")
    for bar, val in zip(bars, importances_norm[::-1]):
        ax.text(bar.get_width() + 0.005, bar.get_y() + bar.get_height() / 2,
                f"{val:.4f} ({val * 100:.2f}%)", va="center", fontsize=9)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "figure_08_feature_importance.png", bbox_inches="tight")
    plt.close(fig)
    print(f"Saved figure_08_feature_importance.png ({len(signals_ordered)} signals)")

    # -----------------------------------------------------------------------
    # Figure 9: Signal Correlation Matrix (7x7)
    # -----------------------------------------------------------------------
    corr_data = report.get("signal_correlations", {})
    n = len(signals_ordered)
    corr_matrix = np.zeros((n, n))
    for i, si in enumerate(signals_ordered):
        for j, sj in enumerate(signals_ordered):
            corr_matrix[i, j] = corr_data.get(si, {}).get(sj, 0.0)

    fig, ax = plt.subplots(figsize=(8, 7))
    cmap = plt.cm.RdBu_r
    vmax = max(abs(corr_matrix.min()), abs(corr_matrix.max()), 1.0)
    im = ax.imshow(corr_matrix, cmap=cmap, vmin=-vmax, vmax=vmax, aspect="auto")
    tick_labels = [SIGNAL_DISPLAY_NAMES.get(s, s) for s in signals_ordered]
    ax.set_xticks(range(n))
    ax.set_xticklabels(tick_labels, rotation=45, ha="right", fontsize=9)
    ax.set_yticks(range(n))
    ax.set_yticklabels(tick_labels, fontsize=9)
    ax.set_title("Phase 5: Signal Correlation Matrix (7 Signals)")
    for i in range(n):
        for j in range(n):
            color = "white" if abs(corr_matrix[i, j]) > 0.5 * vmax else "black"
            ax.text(j, i, f"{corr_matrix[i, j]:.3f}", ha="center", va="center",
                    fontsize=8, color=color)
    plt.colorbar(im, ax=ax, shrink=0.8, label="Pearson Correlation")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "figure_09_signal_correlation.png", bbox_inches="tight")
    plt.close(fig)
    print(f"Saved figure_09_signal_correlation.png ({n}x{n} matrix)")

    # -----------------------------------------------------------------------
    # Figure 10: Signal Distributions (7 signals)
    # -----------------------------------------------------------------------
    dist_data = report.get("signal_distributions", {})
    n_signals = len(signals_ordered)
    ncols = 4
    nrows = (n_signals + ncols - 1) // ncols

    fig, axes = plt.subplots(nrows, ncols, figsize=(14, 4 * nrows))
    axes_flat = axes.flatten() if n_signals > 1 else [axes]

    for idx, sig in enumerate(signals_ordered):
        ax = axes_flat[idx]
        sig_dist = dist_data.get(sig, {})
        benign = sig_dist.get("benign", {})
        malicious = sig_dist.get("malicious", {})

        b_mean = benign.get("mean", 0)
        b_std = benign.get("std", 1)
        m_mean = malicious.get("mean", 0)
        m_std = malicious.get("std", 1)

        x_range = np.linspace(
            min(b_mean - 3 * b_std, m_mean - 3 * m_std),
            max(b_mean + 3 * b_std, m_mean + 3 * m_std),
            200,
        )

        def gaussian(x, mu, sigma):
            if sigma <= 0:
                return np.zeros_like(x)
            return np.exp(-0.5 * ((x - mu) / sigma) ** 2) / (sigma * np.sqrt(2 * np.pi))

        ax.fill_between(x_range, gaussian(x_range, b_mean, b_std), alpha=0.4, color="#4CAF50", label="Benign")
        ax.fill_between(x_range, gaussian(x_range, m_mean, m_std), alpha=0.4, color="#F44336", label="Malicious")
        ax.plot(x_range, gaussian(x_range, b_mean, b_std), color="#4CAF50", linewidth=1.5)
        ax.plot(x_range, gaussian(x_range, m_mean, m_std), color="#F44336", linewidth=1.5)
        ax.set_title(SIGNAL_DISPLAY_NAMES.get(sig, sig), fontsize=10)
        ax.legend(fontsize=7, loc="upper right")
        ax.set_yticks([])
        ax.spines["top"].set_visible(False)
        ax.spines["left"].set_visible(False)

    for idx in range(n_signals, len(axes_flat)):
        axes_flat[idx].set_visible(False)

    fig.suptitle("Phase 5: Signal Distributions (Benign vs Malicious, 7 Signals)", fontsize=13, y=1.02)
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "figure_10_signal_distributions.png", bbox_inches="tight")
    plt.close(fig)
    print(f"Saved figure_10_signal_distributions.png ({n_signals} distributions)")

    # -----------------------------------------------------------------------
    # Figure 13: Ablation Delta (7 signals)
    # -----------------------------------------------------------------------
    ablation = report.get("ablation", {})
    baseline_ba = report.get("best_balanced_accuracy_default_threshold", 0.9322)

    abl_signals = [s for s in PHASE5_SIGNALS if s in ablation]
    abl_deltas = [ablation[s]["delta"] for s in abl_signals]
    abl_bas = [ablation[s]["mean_balanced_accuracy"] for s in abl_signals]
    abl_display = [SIGNAL_DISPLAY_NAMES.get(s, s) for s in abl_signals]

    sorted_idx = np.argsort(abl_deltas)
    abl_signals_sorted = [abl_signals[i] for i in sorted_idx]
    abl_display_sorted = [abl_display[i] for i in sorted_idx]
    abl_deltas_sorted = [abl_deltas[i] for i in sorted_idx]
    abl_bas_sorted = [abl_bas[i] for i in sorted_idx]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    colors_abl = ["#F44336" if d > 0.01 else "#FF9800" if d > 0.001 else "#4CAF50" for d in abl_deltas_sorted]
    bars1 = ax1.barh(abl_display_sorted, abl_deltas_sorted, color=colors_abl, height=0.55, edgecolor="white")
    ax1.axvline(x=0, color="black", linewidth=0.8)
    ax1.set_xlabel("BA Delta (positive = worse)")
    ax1.set_title("Performance Delta When Dropping Signal")
    for bar, val in zip(bars1, abl_deltas_sorted):
        offset = 0.0005 if val >= 0 else -0.0005
        ha = "left" if val >= 0 else "right"
        ax1.text(val + offset, bar.get_y() + bar.get_height() / 2,
                f"{val:+.4f}", va="center", ha=ha, fontsize=9)
    ax1.spines["top"].set_visible(False)
    ax1.spines["right"].set_visible(False)

    colors_ba = ["#1976D2"] * len(abl_bas_sorted)
    bars2 = ax2.barh(abl_display_sorted, abl_bas_sorted, color=colors_ba, height=0.55, edgecolor="white")
    ax2.axvline(x=baseline_ba, color="red", linestyle="--", linewidth=1, label=f"Full model BA={baseline_ba:.4f}")
    ax2.set_xlabel("Balanced Accuracy")
    ax2.set_title("BA After Dropping Signal")
    ax2.set_xlim(min(abl_bas_sorted) - 0.01, 1.0)
    for bar, val in zip(bars2, abl_bas_sorted):
        ax2.text(bar.get_width() + 0.002, bar.get_y() + bar.get_height() / 2,
                f"{val:.4f}", va="center", fontsize=9)
    ax2.legend(fontsize=9)
    ax2.spines["top"].set_visible(False)
    ax2.spines["right"].set_visible(False)

    fig.suptitle("Phase 5: Ablation Study (7 Leakage-Free Signals)", fontsize=13, y=1.02)
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "figure_13_ablation_delta.png", bbox_inches="tight")
    plt.close(fig)
    print(f"Saved figure_13_ablation_delta.png ({len(abl_signals)} signals)")

    # -----------------------------------------------------------------------
    # Figure 7: Per-Tier Detection Rate (RF-only, Phase 5)
    # -----------------------------------------------------------------------
    prefilter_path = RESULTS_DIR / "prefilter_evaluation_report.json"
    if prefilter_path.exists():
        with open(prefilter_path) as f:
            pf_report = json.load(f)
        tier_data_rf = pf_report.get("results_rf_only", {}).get("per_tier_detection_rate", {})
        tier_data_hybrid = pf_report.get("results_hybrid", {}).get("per_tier_detection_rate", {})
    else:
        tier_data_rf = {"1": 0.9277, "2": 0.9681, "3": 0.9920, "4": 0.9412}
        tier_data_hybrid = {"1": 0.9316, "2": 0.9894, "3": 1.0000, "4": 1.0000}

    tier_labels_map = {
        "0": "Tier 0\n(none)", "1": "Tier 1\n(low)", "2": "Tier 2\n(medium)",
        "3": "Tier 3\n(high)", "4": "Tier 4\n(critical)",
    }
    tier_keys = sorted(tier_data_rf.keys(), key=lambda x: int(x))
    tier_keys = [k for k in tier_keys if int(k) > 0]
    tier_names = [tier_labels_map.get(k, f"Tier {k}") for k in tier_keys]
    rf_vals = [tier_data_rf[k] for k in tier_keys]
    hybrid_vals = [tier_data_hybrid.get(k, tier_data_rf[k]) for k in tier_keys]

    fig, ax = plt.subplots(figsize=(9, 5))
    x_pos = np.arange(len(tier_keys))
    width = 0.35
    bars1 = ax.bar(x_pos - width / 2, rf_vals, width, label="RF-only", color="#90CAF9", edgecolor="white")
    bars2 = ax.bar(x_pos + width / 2, hybrid_vals, width, label="Hybrid (RF + Pre-filter)", color="#1565C0", edgecolor="white")
    ax.set_xticks(x_pos)
    ax.set_xticklabels(tier_names, fontsize=10)
    ax.set_ylabel("Detection Rate")
    ax.set_title("Phase 5: Per-Tier Detection Rate")
    ax.set_ylim(0, 1.15)
    ax.axhline(y=0.85, color="green", linestyle="--", alpha=0.6, linewidth=1, label="85% target")
    for bar, val in zip(bars1, rf_vals):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.015,
                f"{val:.3f}", ha="center", fontsize=9)
    for bar, val in zip(bars2, hybrid_vals):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.015,
                f"{val:.3f}", ha="center", fontsize=9)
    ax.legend(fontsize=9)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "figure_07_per_tier_detection.png", bbox_inches="tight")
    plt.close(fig)
    print(f"Saved figure_07_per_tier_detection.png")

    print(f"\nAll Phase 5 figures saved to {FIGURES_DIR}/")
    print("  figure_07_per_tier_detection.png")
    print("  figure_08_feature_importance.png")
    print("  figure_09_signal_correlation.png")
    print("  figure_10_signal_distributions.png")
    print("  figure_13_ablation_delta.png")


if __name__ == "__main__":
    generate_figures()
